# Generated by Django 6.0.3 on 2026-03-05 08:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_costos', '0001_initial'),
        ('core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('cliente_rif', models.CharField(blank=True, max_length=15, verbose_name='RIF del cliente')),
                ('cliente_direccion', models.TextField(blank=True, verbose_name='Dirección del cliente')),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del cliente')),
                ('cliente_contacto', models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto')),
                ('nombre_proyecto', models.CharField(max_length=200, verbose_name='Nombre del proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción del alcance')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CONVERTIDA', 'Convertida a proyecto')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_vencimiento', models.DateField(verbose_name='Válida hasta')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('moneda', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('margen_utilidad_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Margen de utilidad (%)')),
                ('utilidad_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Utilidad')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('terminos_condiciones', models.TextField(blank=True, verbose_name='Términos y condiciones')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas (no visible al cliente)')),
                ('observaciones_cliente', models.TextField(blank=True, verbose_name='Observaciones del cliente')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='core.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PartidaCotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('unidad', models.CharField(max_length=20, verbose_name='Unidad')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoría/Sección')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='cotizaciones.cotizacion')),
                ('item_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_cotizacion', to='bd_costos.itemcosto', verbose_name='Ítem de BD de costos')),
            ],
            options={
                'verbose_name': 'Partida de cotización',
                'verbose_name_plural': 'Partidas de cotización',
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['empresa', 'estado'], name='cotizacione_empresa_eb156b_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['empresa', 'fecha_creacion'], name='cotizacione_empresa_d32e51_idx'),
        ),
    ]
