# Generated by Django 6.0.3 on 2026-03-18 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_equipo', models.CharField(max_length=50, verbose_name='Código / TAG')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del equipo')),
                ('tipo', models.CharField(choices=[('BOMBA', 'Bomba'), ('CALDERIN', 'Calderín'), ('TANQUE', 'Tanque'), ('TUBERIA', 'Tubería'), ('INTERCAMBIADOR', 'Intercambiador de calor'), ('COMPRESOR', 'Compresor'), ('MOTOR', 'Motor'), ('VALVULA', 'Válvula'), ('ESTRUCTURA', 'Estructura metálica'), ('OTRO', 'Otro')], default='OTRO', max_length=30, verbose_name='Tipo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('serial', models.CharField(blank=True, max_length=100, verbose_name='Serial')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación / Planta')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área / Sección')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Cliente propietario')),
                ('cliente_rif', models.CharField(blank=True, max_length=15, verbose_name='RIF del cliente')),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('EN_REPARACION', 'En reparación'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('RETIRADO', 'Retirado')], default='OPERATIVO', max_length=20, verbose_name='Estado')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('frecuencia_mtto_dias', models.PositiveIntegerField(blank=True, help_text='Cada cuántos días requiere mantenimiento preventivo', null=True, verbose_name='Frecuencia de mtto. (días)')),
                ('proximo_mtto', models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento')),
                ('especificaciones', models.TextField(blank=True, verbose_name='Especificaciones técnicas')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Activo del cliente',
                'verbose_name_plural': 'Activos del cliente',
                'ordering': ['cliente_nombre', 'codigo_equipo'],
                'indexes': [models.Index(fields=['empresa', 'cliente_nombre'], name='activos_act_empresa_67bd87_idx'), models.Index(fields=['empresa', 'tipo'], name='activos_act_empresa_25eb28_idx')],
                'unique_together': {('empresa', 'codigo_equipo')},
            },
        ),
    ]
