# Generated by Django 6.0.3 on 2026-03-05 08:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        ('cotizaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Cliente')),
                ('cliente_rif', models.CharField(blank=True, max_length=15, verbose_name='RIF del cliente')),
                ('cliente_contacto', models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto')),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del cliente')),
                ('fecha_inicio_planeada', models.DateField(verbose_name='Inicio planeado')),
                ('fecha_inicio_real', models.DateField(blank=True, null=True, verbose_name='Inicio real')),
                ('fecha_fin_planeada', models.DateField(verbose_name='Fin planeado')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fin real')),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor del contrato')),
                ('moneda', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'Planificación'), ('EN_EJECUCION', 'En Ejecución'), ('PAUSADO', 'Pausado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PLANIFICACION', max_length=20, verbose_name='Estado')),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% de avance')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cotizacion_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecto', to='cotizaciones.cotizacion', verbose_name='Cotización de origen')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='core.empresa')),
                ('gerente_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_como_gerente', to=settings.AUTH_USER_MODEL, verbose_name='Gerente de proyecto')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_como_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PartidaProyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('unidad', models.CharField(max_length=20, verbose_name='Unidad')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoría/Sección')),
                ('cantidad_presupuestada', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad presupuestada')),
                ('precio_unitario_presupuestado', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='P.U. presupuestado')),
                ('costo_presupuestado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Costo presupuestado')),
                ('cantidad_ejecutada', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Cantidad ejecutada')),
                ('costo_real', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Costo real')),
                ('estado', models.CharField(choices=[('NO_INICIADA', 'No iniciada'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada')], default='NO_INICIADA', max_length=20, verbose_name='Estado')),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% avance')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Partida del proyecto',
                'verbose_name_plural': 'Partidas del proyecto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCambio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField(verbose_name='N° de orden')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('justificacion', models.TextField(verbose_name='Justificación')),
                ('impacto_costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Impacto en costo ($)')),
                ('impacto_tiempo_dias', models.IntegerField(default=0, verbose_name='Impacto en tiempo (días)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('observaciones_aprobacion', models.TextField(blank=True, verbose_name='Observaciones de aprobación')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_cambio', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Orden de cambio',
                'verbose_name_plural': 'Órdenes de cambio',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='FotoProyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='proyectos/%Y/%m/', verbose_name='Imagen')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Foto del proyecto',
                'verbose_name_plural': 'Fotos del proyecto',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha del avance')),
                ('cantidad_ejecutada_dia', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad ejecutada')),
                ('costo_dia', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo del día')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='proyectos.partidaproyecto')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_avance', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de avance',
                'verbose_name_plural': 'Registros de avance',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['empresa', 'estado'], name='proyectos_p_empresa_e91805_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordencambio',
            unique_together={('proyecto', 'numero')},
        ),
    ]
