# Generated by Django 6.0.3 on 2026-03-18 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_costos', '0001_initial'),
        ('core', '0001_initial'),
        ('proyectos', '0002_proyecto_activo_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoTrabajador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cargo')),
                ('nivel', models.CharField(choices=[('AYUDANTE', 'Ayudante'), ('OFICIAL', 'Oficial'), ('MAESTRO', 'Maestro'), ('ESPECIALISTA', 'Especialista'), ('SUPERVISOR', 'Supervisor'), ('INGENIERO', 'Ingeniero')], default='OFICIAL', max_length=20, verbose_name='Nivel')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('costo_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por hora ($)')),
                ('moneda', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='core.empresa')),
                ('item_costo', models.OneToOneField(blank=True, help_text='Ítem de mano de obra vinculado en la BD de costos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_origen', to='bd_costos.itemcosto', verbose_name='Ítem en BD de Costos')),
            ],
            options={
                'verbose_name': 'Cargo de trabajador',
                'verbose_name_plural': 'Cargos de trabajadores',
                'ordering': ['nivel', 'nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='HistorialCostoHH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costo_hora_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_hora_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='nomina.cargotrabajador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_costo_hh', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de costo HH',
                'verbose_name_plural': 'Historial de costos HH',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cantidad_trabajadores', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad de trabajadores')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas trabajadas')),
                ('costo_hora_aplicado', models.DecimalField(decimal_places=2, help_text='Snapshot del costo al momento del registro', max_digits=10, verbose_name='Costo/hora aplicado')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo total HH')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_hh', to='nomina.cargotrabajador', verbose_name='Cargo')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_hh', to='proyectos.partidaproyecto', verbose_name='Partida del proyecto')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_hh', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de horas hombre',
                'verbose_name_plural': 'Registros de horas hombre',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
