# Generated by Django 6.0.3 on 2026-03-05 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_costo', to='core.empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='bd_costos.categoriaitem', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría de ítem',
                'verbose_name_plural': 'Categorías de ítems',
                'ordering': ['orden', 'codigo', 'nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ItemCosto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('MANO_OBRA', 'Mano de Obra'), ('EQUIPO', 'Equipo/Maquinaria'), ('SUBCONTRATO', 'Subcontrato'), ('OTROS', 'Otros')], default='MATERIAL', max_length=20, verbose_name='Tipo')),
                ('unidad', models.CharField(choices=[('m2', 'm²'), ('m3', 'm³'), ('ml', 'ml (metro lineal)'), ('kg', 'kg'), ('ton', 'Tonelada'), ('un', 'Unidad'), ('lote', 'Lote'), ('dia', 'Día'), ('hora', 'Hora'), ('mes', 'Mes'), ('pie', 'Pie'), ('pulg', 'Pulgada'), ('otro', 'Otra')], default='un', max_length=10, verbose_name='Unidad')),
                ('unidad_custom', models.CharField(blank=True, max_length=20, verbose_name='Unidad personalizada')),
                ('precio_actual', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio actual')),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('VES', 'VES')], default='USD', max_length=3, verbose_name='Moneda')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Última actualización')),
                ('especificaciones', models.TextField(blank=True, verbose_name='Especificaciones técnicas')),
                ('proveedor_preferido', models.CharField(blank=True, max_length=150, verbose_name='Proveedor preferido')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='bd_costos.categoriaitem', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_costo', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Ítem de costo',
                'verbose_name_plural': 'Ítems de costo',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('precio', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio')),
                ('moneda', models.CharField(max_length=3, verbose_name='Moneda')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_precio', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='bd_costos.itemcosto')),
            ],
            options={
                'verbose_name': 'Historial de precio',
                'verbose_name_plural': 'Historial de precios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='itemcosto',
            index=models.Index(fields=['empresa', 'tipo'], name='bd_costos_i_empresa_ebeb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcosto',
            index=models.Index(fields=['empresa', 'descripcion'], name='bd_costos_i_empresa_8b1906_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcosto',
            unique_together={('empresa', 'codigo')},
        ),
    ]
